/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  profile: () => import("@/views/_builtin/profile/index.vue"),
  ai_chat: () => import("@/views/ai/chat/index.vue"),
  ai_suggestion: () => import("@/views/ai/suggestion/index.vue"),
  "env_alert-log": () => import("@/views/env/alert-log/index.vue"),
  "env_alert-rule": () => import("@/views/env/alert-rule/index.vue"),
  env_device: () => import("@/views/env/device/index.vue"),
  "env_env-data": () => import("@/views/env/env-data/index.vue"),
  farming_crop: () => import("@/views/farming/crop/index.vue"),
  "farming_farming-log": () => import("@/views/farming/farming-log/index.vue"),
  farming_farmland: () => import("@/views/farming/farmland/index.vue"),
  farming_farmland_list: () => import("@/views/farming/farmland/list/index.vue"),
  farming_farmland_map: () => import("@/views/farming/farmland/map/index.vue"),
  home: () => import("@/views/home/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
};
