/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'env',
    path: '/env',
    component: 'layout.base',
    meta: {
      title: 'env',
      i18nKey: 'route.env',
      icon: 'mdi:monitor-eye'
    },
    children: [
      {
        name: 'env_alert-rule',
        path: '/env/alert-rule',
        component: 'view.env_alert-rule',
        meta: {
          title: 'env_alert-rule',
          i18nKey: 'route.env_alert-rule',
          icon: 'mdi:table-alert'
        }
      },
      {
        name: 'env_device',
        path: '/env/device',
        component: 'view.env_device',
        meta: {
          title: 'env_device',
          i18nKey: 'route.env_device',
          icon: 'mdi:mobile-devices'
        }
      },
      {
        name: 'env_env-data',
        path: '/env/env-data',
        component: 'view.env_env-data',
        meta: {
          title: 'env_env-data',
          i18nKey: 'route.env_env-data',
          icon: 'mdi:data'
        }
      }
    ]
  },
  {
    name: 'farming',
    path: '/farming',
    component: 'layout.base',
    meta: {
      title: 'farming',
      i18nKey: 'route.farming',
      icon: 'mdi:table-user'
    },
    children: [
      {
        name: 'farming_crop',
        path: '/farming/crop',
        component: 'view.farming_crop',
        meta: {
          title: 'farming_crop',
          i18nKey: 'route.farming_crop',
          icon: 'material-symbols:potted-plant-outline'
        }
      },
      {
        name: 'farming_farming-log',
        path: '/farming/farming-log',
        component: 'view.farming_farming-log',
        meta: {
          title: 'farming_farming-log',
          i18nKey: 'route.farming_farming-log',
          icon: 'mdi:account-clock-outline'
        }
      },
      {
        name: 'farming_farmland',
        path: '/farming/farmland',
        component: 'view.farming_farmland',
        meta: {
          title: 'farming_farmland',
          i18nKey: 'route.farming_farmland',
          icon: 'material-symbols:backup-table'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'carbon:cloud-service-management'
    },
    children: [
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user',
          icon: 'ic:round-manage-accounts'
        }
      }
    ]
  }
];
